-- MySQL Script generated by MySQL Workbench
-- mié 15 mar 2023 13:43:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Avion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avion` (
  `IDavion` INT NOT NULL,
  `Modelo` VARCHAR(45) NULL,
  `Capacidad total de pasajeros` VARCHAR(45) NULL,
  PRIMARY KEY (`IDavion`),
  UNIQUE INDEX `Modelo_UNIQUE` (`Modelo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vuelo` (
  `Num Vuelo` INT NOT NULL,
  `Avion que se usara para el vuelo` VARCHAR(45) NULL,
  `Origen` VARCHAR(45) NULL,
  `Destino` VARCHAR(45) NULL,
  `Fecha de salida y llegada` VARCHAR(45) NULL,
  `Hora de salida y llegada` VARCHAR(45) NULL,
  `Avion_IDavion` INT NOT NULL,
  UNIQUE INDEX `Num Vuelo_UNIQUE` (`Num Vuelo` ASC) VISIBLE,
  INDEX `fk_Vuelo_Avion1_idx` (`Avion_IDavion` ASC) VISIBLE,
  CONSTRAINT `fk_Vuelo_Avion1`
    FOREIGN KEY (`Avion_IDavion`)
    REFERENCES `mydb`.`Avion` (`IDavion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `IDreserva` INT NOT NULL,
  `Pasajero` VARCHAR(45) NULL,
  `Fecha de reserva` VARCHAR(45) NULL,
  `Numero de vuelo` VARCHAR(45) NULL,
  `Importe total` VARCHAR(45) NULL,
  PRIMARY KEY (`IDreserva`),
  INDEX `fk_Reserva_Vuelo_idx` (`Fecha de reserva` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Vuelo`
    FOREIGN KEY (`Fecha de reserva`)
    REFERENCES `mydb`.`Vuelo` (`Origen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pasajeros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pasajeros` (
  `DNI/PASAPORTE` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Reserva_IDreserva` INT NOT NULL,
  INDEX `fk_Pasajeros_Reserva1_idx` (`Reserva_IDreserva` ASC) VISIBLE,
  CONSTRAINT `fk_Pasajeros_Reserva1`
    FOREIGN KEY (`Reserva_IDreserva`)
    REFERENCES `mydb`.`Reserva` (`IDreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
