-- MySQL Script generated by MySQL Workbench
-- mié 15 mar 2023 13:46:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Departament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departament` (
  `idDepartament` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idDepartament`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asignatura` (
  `idAsignatura` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Crèdits` VARCHAR(45) NULL,
  `Departament` VARCHAR(45) NULL,
  `Professor` VARCHAR(45) NULL,
  `Departament_idDepartament` INT NOT NULL,
  PRIMARY KEY (`idAsignatura`),
  INDEX `fk_Asignatura_Departament1_idx` (`Departament_idDepartament` ASC) VISIBLE,
  CONSTRAINT `fk_Asignatura_Departament1`
    FOREIGN KEY (`Departament_idDepartament`)
    REFERENCES `mydb`.`Departament` (`idDepartament`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Matrícula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matrícula` (
  `idMatrícula` INT NOT NULL AUTO_INCREMENT,
  `Data` VARCHAR(45) NULL,
  `Alumne` VARCHAR(45) NULL,
  `Assignatura` VARCHAR(45) NULL,
  `Asignatura_idAsignatura` INT NOT NULL,
  PRIMARY KEY (`idMatrícula`),
  INDEX `fk_Matrícula_Asignatura1_idx` (`Asignatura_idAsignatura` ASC) VISIBLE,
  CONSTRAINT `fk_Matrícula_Asignatura1`
    FOREIGN KEY (`Asignatura_idAsignatura`)
    REFERENCES `mydb`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumne` (
  `idAlumne` INT NOT NULL AUTO_INCREMENT,
  `DNI` VARCHAR(45) NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Cognoms` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telèfon` VARCHAR(45) NOT NULL,
  `Adreça` VARCHAR(45) NOT NULL,
  `Matrícula_idMatrícula` INT NOT NULL,
  PRIMARY KEY (`idAlumne`),
  INDEX `fk_Alumne_Matrícula_idx` (`Matrícula_idMatrícula` ASC) VISIBLE,
  CONSTRAINT `fk_Alumne_Matrícula`
    FOREIGN KEY (`Matrícula_idMatrícula`)
    REFERENCES `mydb`.`Matrícula` (`idMatrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professorat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professorat` (
  `idProfessorat` INT NOT NULL AUTO_INCREMENT,
  `DNI` VARCHAR(45) NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Cognoms` VARCHAR(45) NOT NULL,
  `Titulació` VARCHAR(45) NOT NULL,
  `Departament` VARCHAR(45) NOT NULL,
  `EsCapDepartament` VARCHAR(45) NOT NULL,
  `Departament_idDepartament` INT NOT NULL,
  PRIMARY KEY (`idProfessorat`),
  INDEX `fk_Professorat_Departament1_idx` (`Departament_idDepartament` ASC) VISIBLE,
  CONSTRAINT `fk_Professorat_Departament1`
    FOREIGN KEY (`Departament_idDepartament`)
    REFERENCES `mydb`.`Departament` (`idDepartament`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
