-- MySQL Script generated by MySQL Workbench
-- mié 15 mar 2023 13:48:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `DNI` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `VIP/NO VIP` TINYINT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo de poliza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo de poliza` (
  `ID` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendedores` (
  `DNI/NIF` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI/NIF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Poliza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Poliza` (
  `DNI-Client` INT NOT NULL AUTO_INCREMENT,
  `Num poliza` VARCHAR(45) NULL,
  `Importe` VARCHAR(45) NULL,
  `Fecha inicio` VARCHAR(45) NULL,
  `Fecha final` VARCHAR(45) NULL,
  `Tipo pagament` VARCHAR(45) NULL,
  `Tipo poliza` VARCHAR(45) NOT NULL,
  `DNI/NIF` VARCHAR(45) NULL,
  `Tipo de poliza_ID` VARCHAR(45) NOT NULL,
  `Clientes_DNI` INT NOT NULL,
  `Vendedores_DNI/NIF` INT NOT NULL,
  PRIMARY KEY (`DNI-Client`, `Tipo poliza`),
  INDEX `fk_Poliza_Tipo de poliza_idx` (`Tipo de poliza_ID` ASC) VISIBLE,
  INDEX `fk_Poliza_Clientes1_idx` (`Clientes_DNI` ASC) VISIBLE,
  INDEX `fk_Poliza_Vendedores1_idx` (`Vendedores_DNI/NIF` ASC) VISIBLE,
  CONSTRAINT `fk_Poliza_Tipo de poliza`
    FOREIGN KEY (`Tipo de poliza_ID`)
    REFERENCES `mydb`.`Tipo de poliza` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Poliza_Clientes1`
    FOREIGN KEY (`Clientes_DNI`)
    REFERENCES `mydb`.`Clientes` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Poliza_Vendedores1`
    FOREIGN KEY (`Vendedores_DNI/NIF`)
    REFERENCES `mydb`.`Vendedores` (`DNI/NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
