-- MySQL Script generated by MySQL Workbench
-- mié 15 mar 2023 13:45:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Dirección` VARCHAR(45) NOT NULL,
  `Fecha_nacimiento` VARCHAR(45) NOT NULL,
  `Teléfono` VARCHAR(45) NOT NULL,
  `Edad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Línea_de_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Línea_de_ticket` (
  `Identificador` INT NOT NULL,
  `Identificador_Ticket` VARCHAR(45) NULL,
  `Código_producto` VARCHAR(45) NULL,
  `Descripción_producto` VARCHAR(45) NULL,
  `Unidades_descuento` VARCHAR(45) NULL,
  `Precio_Unitario_(IVA)` VARCHAR(45) NULL,
  `Precio_total` VARCHAR(45) NULL,
  PRIMARY KEY (`Identificador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `Identificador` INT NOT NULL,
  `Nº_Factura` VARCHAR(45) NOT NULL,
  `DNI_Empleado` VARCHAR(45) NOT NULL,
  `Fecha` VARCHAR(45) NOT NULL,
  `Hora` VARCHAR(45) NOT NULL,
  `Precio_IVA_incluido` VARCHAR(45) NOT NULL,
  `Empleado_DNI` INT NOT NULL,
  `Línea_de_ticket_Identificador` INT NOT NULL,
  PRIMARY KEY (`Identificador`),
  INDEX `fk_Ticket_Empleado_idx` (`Empleado_DNI` ASC) VISIBLE,
  INDEX `fk_Ticket_Línea_de_ticket1_idx` (`Línea_de_ticket_Identificador` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Empleado`
    FOREIGN KEY (`Empleado_DNI`)
    REFERENCES `mydb`.`Empleado` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Línea_de_ticket1`
    FOREIGN KEY (`Línea_de_ticket_Identificador`)
    REFERENCES `mydb`.`Línea_de_ticket` (`Identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `Código_barras` INT NOT NULL,
  `Precio_Unitario` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(45) NOT NULL,
  `IVA` VARCHAR(45) NOT NULL,
  `Precio_final` VARCHAR(45) NOT NULL,
  `Línea_de_ticket_Identificador` INT NOT NULL,
  PRIMARY KEY (`Código_barras`),
  INDEX `fk_Producto_Línea_de_ticket1_idx` (`Línea_de_ticket_Identificador` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Línea_de_ticket1`
    FOREIGN KEY (`Línea_de_ticket_Identificador`)
    REFERENCES `mydb`.`Línea_de_ticket` (`Identificador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
